from enum import Enum


class tipo_usuario(str, Enum):
    DOCENTE = 'DOCENTE'
    EXTERNO = 'EXTERNO'
    DESENVOLVEDOR = 'DESENVOLVEDOR'

class tipo_registro(str, Enum):
    PATENTE_INVENCAO = 'PATENTE_INVENCAO'      
    MODELO_UTILIDADE = 'MODELO_UTILIDADE'       
    CERTIFICADO_ADICAO = 'CERTIFICADO_ADICAO'   
    MARCA = 'MARCA'
    DESENHO_INDUSTRIAL = 'DESENHO_INDUSTRIAL'
    PROGRAMA_COMPUTADOR = 'PROGRAMA_COMPUTADOR' 
    DIREITO_AUTORAL = 'DIREITO_AUTORAL'
    CULTIVAR = 'CULTIVAR'
    TOPOGRAFIA_CIRCUITO = 'TOPOGRAFIA_CIRCUITO'
    INDICACAO_GEOGRAFICA = 'INDICACAO_GEOGRAFICA'

class categoria_pi(str, Enum):
    CIENCIAS_AGRARIAS = 'CIENCIAS_AGRARIAS'
    CIENCIAS_BIOLOGICAS = 'CIENCIAS_BIOLOGICAS'
    CIENCIAS_DA_SAUDE = 'CIENCIAS_DA_SAUDE'
    CIENCIAS_EXATAS_E_TERRA = 'CIENCIAS_EXATAS_E_TERRA'
    ENGENHARIAS = 'ENGENHARIAS'
    CIENCIAS_HUMANAS = 'CIENCIAS_HUMANAS'
    CIENCIAS_SOCIAIS_APLICADAS = 'CIENCIAS_SOCIAIS_APLICADAS'
    LINGUISTICA_LETRAS_E_ARTES = 'LINGUISTICA_LETRAS_E_ARTES'
    MULTIDISCIPLINAR = 'MULTIDISCIPLINAR'
    OUTROS = 'OUTROS'

class tipo_interesse(str, Enum):
  FINANCIAR = 'FINANCIAR'
  COMPRA = 'COMPRA'
  ASSINATURA = 'ASSINATURA'
