from enum import Enum


class tipo_usuario(str, Enum):
    SERVIDOR = 'SERVIDOR'
    EXTERNO = 'EXTERNO'
    DEV = 'DEV'
    SIND = 'SIND'

class tipo_registro(str, Enum):
    PATENTE_INVENCAO = 'PATENTE_INVENCAO'      
    MODELO_UTILIDADE = 'MODELO_UTILIDADE'       
    CERTIFICADO_ADICAO = 'CERTIFICADO_ADICAO'   
    MARCA = 'MARCA'
    DESENHO_INDUSTRIAL = 'DESENHO_INDUSTRIAL'
    PROGRAMA_COMPUTADOR = 'PROGRAMA_COMPUTADOR' 
    DIREITO_AUTORAL = 'DIREITO_AUTORAL'
    CULTIVAR = 'CULTIVAR'
    TOPOGRAFIA_CIRCUITO = 'TOPOGRAFIA_CIRCUITO'
    INDICACAO_GEOGRAFICA = 'INDICACAO_GEOGRAFICA'

class categoria_pi(str, Enum):
    CIENCIAS_AGRARIAS = 'CIENCIAS_AGRARIAS'
    CIENCIAS_BIOLOGICAS = 'CIENCIAS_BIOLOGICAS'
    CIENCIAS_DA_SAUDE = 'CIENCIAS_DA_SAUDE'
    CIENCIAS_EXATAS_E_TERRA = 'CIENCIAS_EXATAS_E_TERRA'
    ENGENHARIAS = 'ENGENHARIAS'
    CIENCIAS_HUMANAS = 'CIENCIAS_HUMANAS'
    CIENCIAS_SOCIAIS_APLICADAS = 'CIENCIAS_SOCIAIS_APLICADAS'
    LINGUISTICA_LETRAS_E_ARTES = 'LINGUISTICA_LETRAS_E_ARTES'
    MULTIDISCIPLINAR = 'MULTIDISCIPLINAR'
    OUTROS = 'OUTROS'

class tipo_interesse(str, Enum):
  FINANCIAR = 'FINANCIAR'
  COMPRA = 'COMPRA'
  ASSINATURA = 'ASSINATURA'

class tipo_status_email(str, Enum):
    ATIVO = 'ATIVO'
    ENCERRADO = 'ENCERRADO'

class tipo_funcao(str, Enum):
    COORDENADOR_COORDENADORA = 'COORDENADOR_COORDENADORA'
    PESQUISADOR_PESQUISADORA = 'PESQUISADOR_PESQUISADORA'
    COLOBORADOR_COLOBORADORA = 'COLOBORADOR_COLOBORADORA'